### ISSUE TITLE
"level" is null when upgrading and expanding a 1.16.5 Nether to 1.18.1

### ISSUE THREAD

**Issue by mov51** [PaperMC/DataConverter#2]
I'm upgrading my world from 1.16.5 to 1.18.1 and adding new terrain using Chunky to the edge of my current world. 
I was able to generate my Overworld without any issues, but when generating my Nether I get the following log on [Paper build #100](https://mcpaste.io/f14da39b0a35a1f4) and this [log on Paper build #84](https://mcpaste.io/9d267a29989ed386) where I originally discovered the issue. I reached out to the Paper discord in the 1.18 experimental channel [here](https://discord.com/channels/289587909051416579/914372738179825664/923443578355720212) and the Chunky Dev (pop4959) made sure that it was not a Chunky issue. 

*It is worth noting that the generation task stopping and the errors failing to print after a certain point was a Chunky bug that pop4959 has since released an update to fix. Both of the above logs were made without the new patch.*

## behavior
According to the logs, the errors are starting at around chunk coordinate 92 and then moving down the z axis starting from chunk 91. That chunk area is exactly where my world border was before I started expanding the world as seen on line 155 of my first two logs. What's weird about that location is that it's exactly where my border would have been in 1.16.5, so there are definitely chunks there and a bit past it too. 

Loading chunks as a player doesn't cause any errors at all, and starting the generation task again doesn't cause those chunks to error again. Even if I load the entire Nether as a player and let Chunky go over it again I still don't get any errors. 

## logs
[Here is a log](https://mcpaste.io/369de6fa2296cbc2) where I was able to get the same errors with a freshly generated 1.16.5 Nether with the same world border location. When using the new update of Chunky that fixes the generation task crashing the errors seem to stop after it gets past the world border ring.

### Example worlds:
- The original world I tried to upgrade that has been used for just over a year. 
  - [Google Drive Link](https://drive.google.com/file/d/1hFBIqGn_VE8uKqjrQFerhUJwgx1Cnlex/view?usp=sharing)
- A freshly generated world with a matching world border.
  - ~~[Google Drive Link](https://drive.google.com/file/d/1m32AoLN_49_UG2jILPL3X7JJj2E6r6uD/view?usp=sharing)~~
  - [Corrected Google Drive Link](https://drive.google.com/file/d/1y02UdkCVAsnsT1ln4VVkrUh9uCJU2dEj/view?usp=sharing)

The error that shows in the log matches what I show below but the chunk coordinate below changes.
```
[Paper Async Chunk Task Thread #2/ERROR]: Could not apply datafixers for chunk task: Chunk task: class:com.destroystokyo.paper.io.chunk.ChunkLoadTask, for world 'world_nether', (96,92), hashcode:1909237420, priority: -1
--
176 | java.lang.NullPointerException: Cannot invoke "ca.spottedleaf.dataconverter.types.MapType.hasKey(Object)" because "level" is null
177 | at ca.spottedleaf.dataconverter.minecraft.versions.V2842$1.convert(V2842.java:25) ~[paper-1.18.1.jar:git-Paper-100]
178 | at ca.spottedleaf.dataconverter.minecraft.versions.V2842$1.convert(V2842.java:17) ~[paper-1.18.1.jar:git-Paper-100]
179 | at ca.spottedleaf.dataconverter.minecraft.datatypes.MCDataType.convert(MCDataType.java:79) ~[paper-1.18.1.jar:git-Paper-100]
180 | at ca.spottedleaf.dataconverter.minecraft.datatypes.MCDataType.convert(MCDataType.java:13) ~[paper-1.18.1.jar:git-Paper-100]
181 | at ca.spottedleaf.dataconverter.minecraft.MCDataConverter.convert(MCDataConverter.java:79) ~[paper-1.18.1.jar:git-Paper-100]
182 | at ca.spottedleaf.dataconverter.minecraft.MCDataConverter.convertTag(MCDataConverter.java:40) ~[paper-1.18.1.jar:git-Paper-100]
183 | at net.minecraft.world.level.chunk.storage.ChunkStorage.upgradeChunkTag(ChunkStorage.java:115) ~[?:?]
184 | at com.destroystokyo.paper.io.chunk.ChunkLoadTask.executeTask(ChunkLoadTask.java:94) ~[paper-1.18.1.jar:git-Paper-100]
185 | at com.destroystokyo.paper.io.chunk.ChunkLoadTask.run(ChunkLoadTask.java:38) ~[paper-1.18.1.jar:git-Paper-100]
186 | at com.destroystokyo.paper.io.QueueExecutorThread.pollTasks(QueueExecutorThread.java:105) ~[paper-1.18.1.jar:git-Paper-100]
187 | at com.destroystokyo.paper.io.QueueExecutorThread.run(QueueExecutorThread.java:38) ~[paper-1.18.1.jar:git-Paper-100]
```

**Comment by Spottedleaf** [comment]
Can't produce locally with the provided world
If "level" is null then the chunk is completely corrupt, make sure you're running it on the world provided to me and nothing is getting corrupted along the way

**Comment by mov51** [comment]
I was able to replicate the issue on both of the worlds provided **only** when loading the chunks via Chunky, not via player. 
I don't have another plugin that loads chunks in a similar way to Chunky to test with but pop4959 did spend time with the world replicating the issue and determined that the error isn't caused by Chunky, just triggered by it.

**Comment by NoahvdAa** [comment]
I tried reproducing this using chunky on your fresh world, with a radius of 1920, but everything worked without a problem.

**Comment by pop4959** [comment]
I was able to produce on the original world, but not the fresh world provided. I was however still able to create a completely fresh server and world myself on 1.16.5-794 and get these errors when loading it up in 1.18.1-101. Also interestingly it does not seem to happen for the exact same set of chunks each time, given an exact copy of the world.

**Comment by mov51** [comment]
Ah, that's my fault. I messed up when transferring the fresh world. Here's a [corrected](https://drive.google.com/file/d/1y02UdkCVAsnsT1ln4VVkrUh9uCJU2dEj/view?usp=sharing) and triple tested version that I've also changed in the original post.

**Comment by Spottedleaf** [comment]
Fixed by https://github.com/PaperMC/Paper/commit/22be4d5c603f4046e2e6bea3fd7e139e3085b7b4

It wasn't a dataconverter problem, just an error in the async IO patch

**Comment by mov51** [comment]
Whooo! Thank you for sorting it out <3
