### ISSUE TITLE
Connecting blocks don't upgrade properly with custom dimension types

### ISSUE THREAD

**Issue by Pablete1234** [PaperMC/DataConverter#22]
When upgrading a 1.8 world with fences, iron bars glass panes, etc, paper does not connect them except on chunk borders:
![image](https://github.com/user-attachments/assets/ab545806-466f-487a-9c0d-dfa791990c5c)

This only happens when using a custom dimension type, if it is left unchanged (minecraft:overworld) then it does connect them.

The dimension type is being modified to a custom type to keep the min world height at 0 to keep the maps' gameplay the same (ie: no building under y=0). Blocks not connecting seems to be the only thing broken due to this, it is otherwise working fine.

Please note, i'm not totally sure if this is a bug or intended behavior. If it is intended that non-default dimension types won't get their connections updated, any hints, tips, workarounds, or pointers as to why this is like it is would be appreciated.

For reference, the map itself can be found in <https://github.com/PGMDev/Maps/tree/master/The%20Fenland> (level.dat + region folder only)

**Comment by Spottedleaf** [comment]
The custom dimension type must have the min world height set to 0 and the max set to 256 (i.e through a datapack) in order for the conversion to work properly, as connecting fences is the responsibility of the post-processor which runs after chunks are loaded.

**Comment by Pablete1234** [comment]
@Spottedleaf i've identified the root cause of the issue:
https://github.com/PaperMC/DataConverter/blob/master/src/main/java/ca/spottedleaf/dataconverter/minecraft/versions/V2832.java#L668

The indices in UpgradeData are *always* shifted 4 chunks up when going from 1.17 to 1.18, regardless of the world min height. This causes the server to later have the wrong height for the blocks it needs to update, and it's why fences are left un-updated.

With default dimension type (the section i=4 is at y=0, proper block is updated at y=8):
![Image](https://github.com/user-attachments/assets/35f4a7ff-645b-4e76-bfd5-1d8a9c7d7256)



With custom dimension type that has min world y = 0 (the section i=4 is at y=64, which is not correct):
![Image](https://github.com/user-attachments/assets/fcebce45-0d28-4096-9e7e-af2fe04c7120)

**Comment by Spottedleaf** [comment]
I don't see where our logic differs from Vanilla here. If the world doesn't have extended height, it should not have the UpgradeData offset.

**Comment by Pablete1234** [comment]
I ended up being able to workaround the issue by adding my own data converter to the pipeline and manually modifying the dimension in the "__context" data key for the chunk, causing it not to shift anymore
