### ISSUE TITLE
V2841 incorrectly reads block state property values as integers and booleans

### ISSUE THREAD

**Issue by Earthcomputer** [PaperMC/DataConverter#6]
[Here](https://github.com/PaperMC/DataConverter/blob/5a0cefb45e246ef36901fb62448571edd82e7296/src/main/java/ca/spottedleaf/dataconverter/minecraft/versions/V2841.java#L147-L152).

Vanilla does this too, but it's incorrect as block state property values are always strings in NBT form. I think it's worth looking into whether this causes an issue, or whether fixing it would also cause an issue.

**Comment by Spottedleaf** [comment]
If they are stored in string form, then this would cause the pending fluid tick list (sometime during or after 1.13 this was added to protochunks) to be obliterated as the tick logic will refuse the tick if the fluid isn't the same.

**Comment by Earthcomputer** [comment]
I have a feeling that that's exactly what's happening, and that it's rare enough that people have accepted it whenever they saw it as "one of those weird Minecraft things".

**Comment by Spottedleaf** [comment]
I would take a fix for this if you were to write one, but would generally be more interested if this happens in other areas of the code - this isn't something that occurred to me when porting the converters over at all really.

**Comment by Earthcomputer** [comment]
I didn't find any other instances of this. I may have missed one though·

**Comment by Spottedleaf** [comment]
Resolved in https://github.com/PaperMC/DataConverter/commit/31387432cacf86b8e76362c6d7de44c5104afbf1
